import { readFileSync } from 'fs';
import { join } from 'path';
import prisma from '../src/db/prisma';

interface BookmarkData {
  id: string;
  url: string;
  title: string;
  domain: string;
  contentType: string;
  tags: string[];
  summary: string;
  createdAt: string;
  updatedAt: string;
  processedAt?: string;
  embeddedAt?: string;
  embedding: number[];
}

interface ImportData {
  bookmarks: BookmarkData[];
}

async function importBookmarks() {
  console.log('🔄 Starting bookmark import...\n');

  // Read JSON file
  const jsonPath = join(__dirname, '../../frontend/.data/bookmarks.json');
  const data: ImportData = JSON.parse(readFileSync(jsonPath, 'utf-8'));

  console.log(`📊 Found ${data.bookmarks.length} bookmarks to import\n`);

  // Get or create default user
  let user = await prisma.user.findFirst();
  if (!user) {
    console.log('👤 Creating default user...');
    user = await prisma.user.create({
      data: {
        email: 'user@smartbookmarks.local',
        passwordHash: 'placeholder', // User can set password later
      },
    });
    console.log(`✓ Created user: ${user.email}\n`);
  } else {
    console.log(`✓ Using existing user: ${user.email}\n`);
  }

  let imported = 0;
  let skipped = 0;

  for (const bookmark of data.bookmarks) {
    try {
      // Check if bookmark already exists
      const existing = await prisma.bookmark.findFirst({
        where: { url: bookmark.url, userId: user.id },
      });

      if (existing) {
        console.log(`⏭  Skipped (exists): ${bookmark.title}`);
        skipped++;
        continue;
      }

      // Create bookmark
      const createdBookmark = await prisma.bookmark.create({
        data: {
          userId: user.id,
          url: bookmark.url,
          title: bookmark.title,
          domain: bookmark.domain,
          summary: bookmark.summary,
          contentType: bookmark.contentType as any,
          status: 'completed',
          embedding: bookmark.embedding,
          createdAt: new Date(bookmark.createdAt),
          updatedAt: new Date(bookmark.updatedAt),
          processedAt: bookmark.processedAt ? new Date(bookmark.processedAt) : null,
        },
      });

      // Create or link tags
      if (bookmark.tags && bookmark.tags.length > 0) {
        for (const tagName of bookmark.tags) {
          const normalizedName = tagName.toLowerCase().trim();

          // Get or create tag
          let tag = await prisma.tag.findFirst({
            where: {
              userId: user.id,
              normalizedName,
            },
          });

          if (!tag) {
            tag = await prisma.tag.create({
              data: {
                userId: user.id,
                name: tagName,
                normalizedName,
              },
            });
          }

          // Link tag to bookmark
          await prisma.bookmarkTag.create({
            data: {
              bookmarkId: createdBookmark.id,
              tagId: tag.id,
              autoGenerated: true,
            },
          });
        }
      }

      console.log(`✓ Imported: ${bookmark.title}`);
      imported++;
    } catch (error) {
      console.error(`✗ Failed to import: ${bookmark.title}`, error);
    }
  }

  console.log(`\n📊 Import Summary:`);
  console.log(`   ✓ Imported: ${imported}`);
  console.log(`   ⏭  Skipped: ${skipped}`);
  console.log(`   📚 Total: ${data.bookmarks.length}`);

  await prisma.$disconnect();
}

importBookmarks().catch((error) => {
  console.error('Import failed:', error);
  process.exit(1);
});
