import { PrismaClient } from '@prisma/client';
import Redis from 'ioredis';
import OpenAI from 'openai';
import { WikidataClient } from '../clients/WikidataClient';
const jaroWinkler = require('jaro-winkler');

// Core interfaces
export interface CanonicalEntity {
  id: string;
  canonicalName: string;
  aliases: string[];
  wikidataId?: string;
  confidence: number;
  method: 'cache' | 'fuzzy' | 'wikidata' | 'llm' | 'new';
}

export interface CanonicalConcept {
  id: string;
  canonicalName: string;
  aliases: string[];
  description?: string;
  confidence: number;
  method: 'cache' | 'fuzzy' | 'semantic' | 'llm' | 'new';
}

export class CanonicalizationService {
  private redis: Redis;
  private prisma: PrismaClient;
  private openai: OpenAI;
  private wikidataClient: WikidataClient;

  constructor() {
    this.redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');
    this.prisma = new PrismaClient();
    this.openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    this.wikidataClient = new WikidataClient();
  }

  /**
   * Resolve an entity to its canonical form using 5-stage pipeline
   */
  async resolveEntity(
    name: string,
    type: string,
    context: string,
    userId: string
  ): Promise<CanonicalEntity> {
    // Stage 1: Cache check
    const cacheKey = this.getCacheKey('entity', type, name);
    const cached = await this.checkCache(cacheKey);
    if (cached) {
      return cached as CanonicalEntity;
    }

    // Stage 2: Fuzzy database match
    const fuzzyMatch = await this.fuzzyMatchEntity(name, type, userId);
    if (fuzzyMatch) {
      await this.cacheResult(cacheKey, fuzzyMatch);
      return fuzzyMatch;
    }

    // Stage 3: Wikidata lookup (temporarily disabled - needs better query precision)
    // TODO: Improve Wikidata SPARQL queries for more accurate matches
    // const wikidataMatch = await this.wikidataLookup(name, type);
    // if (wikidataMatch) {
    //   await this.cacheResult(cacheKey, wikidataMatch);
    //   return wikidataMatch;
    // }

    // Stage 4: LLM canonicalization
    const llmResult = await this.llmCanonicalize(name, context, 'entity', type);

    // Stage 5: Create new entity with canonical name
    const newEntity: CanonicalEntity = {
      id: '', // Will be generated by caller
      canonicalName: llmResult.canonicalName,
      aliases: [name],
      confidence: 0.95,
      method: 'llm',
    };

    await this.cacheResult(cacheKey, newEntity);
    return newEntity;
  }

  /**
   * Resolve a concept to its canonical form using 5-stage pipeline
   */
  async resolveConcept(
    name: string,
    description: string,
    embedding: number[] | null,
    userId: string
  ): Promise<CanonicalConcept> {
    // Stage 1: Cache check
    const cacheKey = this.getCacheKey('concept', 'concept', name);
    const cached = await this.checkCache(cacheKey);
    if (cached) {
      return cached as CanonicalConcept;
    }

    // Stage 2: Fuzzy match (semantic if embedding provided)
    const fuzzyMatch = await this.fuzzyMatchConcept(name, description, embedding, userId);
    if (fuzzyMatch) {
      await this.cacheResult(cacheKey, fuzzyMatch);
      return fuzzyMatch;
    }

    // Stage 3: LLM canonicalization (no Wikidata for concepts)
    const llmResult = await this.llmCanonicalize(name, description, 'concept');

    // Stage 4: Create new concept with canonical name
    const newConcept: CanonicalConcept = {
      id: '', // Will be generated by caller
      canonicalName: llmResult.canonicalName,
      aliases: [name],
      description: description || undefined,
      confidence: 0.95,
      method: 'llm',
    };

    await this.cacheResult(cacheKey, newConcept);
    return newConcept;
  }

  // ============= PRIVATE METHODS =============

  /**
   * Stage 1: Check Redis cache
   */
  private async checkCache(key: string): Promise<CanonicalEntity | CanonicalConcept | null> {
    try {
      const cached = await this.redis.get(key);
      if (cached) {
        return JSON.parse(cached);
      }
    } catch (error) {
      console.error('Cache check failed:', error);
    }
    return null;
  }

  /**
   * Generate cache key for entity/concept
   */
  private getCacheKey(type: 'entity' | 'concept', subtype: string, name: string): string {
    const normalized = name.toLowerCase().trim();
    return `canonical:${type}:${subtype}:${normalized}`;
  }

  /**
   * Stage 2: Fuzzy match entities using Jaro-Winkler similarity
   */
  private async fuzzyMatchEntity(
    name: string,
    type: string,
    userId: string
  ): Promise<CanonicalEntity | null> {
    try {
      // Get top 50 entities by popularity for this type
      const candidates = await this.prisma.entity.findMany({
        where: {
          userId,
          entityType: type,
        },
        orderBy: { popularity: 'desc' },
        take: 50,
      });

      let bestMatch: { entity: any; similarity: number } | null = null;
      const threshold = 0.85;

      for (const candidate of candidates) {
        // Check canonical name similarity
        const similarity = jaroWinkler(
          name.toLowerCase(),
          candidate.canonicalName.toLowerCase()
        );

        if (similarity >= threshold) {
          if (!bestMatch || similarity > bestMatch.similarity) {
            bestMatch = { entity: candidate, similarity };
          }
        }

        // Also check aliases
        for (const alias of candidate.aliases || []) {
          const aliasSim = jaroWinkler(name.toLowerCase(), alias.toLowerCase());
          if (aliasSim >= threshold && (!bestMatch || aliasSim > bestMatch.similarity)) {
            bestMatch = { entity: candidate, similarity: aliasSim };
          }
        }
      }

      if (bestMatch) {
        return {
          id: bestMatch.entity.id,
          canonicalName: bestMatch.entity.canonicalName,
          aliases: bestMatch.entity.aliases || [],
          wikidataId: bestMatch.entity.wikidataId || undefined,
          confidence: bestMatch.similarity,
          method: 'fuzzy',
        };
      }
    } catch (error) {
      console.error('Fuzzy match entity failed:', error);
    }

    return null;
  }

  /**
   * Stage 2: Fuzzy match concepts (string similarity + semantic if embedding provided)
   */
  private async fuzzyMatchConcept(
    name: string,
    description: string,
    embedding: number[] | null,
    userId: string
  ): Promise<CanonicalConcept | null> {
    try {
      // If embedding provided, try semantic similarity first
      if (embedding) {
        const semanticMatch = await this.semanticMatchConcept(embedding, userId);
        if (semanticMatch) return semanticMatch;
      }

      // Fallback to string similarity
      const candidates = await this.prisma.concept.findMany({
        where: { userId },
        orderBy: { popularity: 'desc' },
        take: 50,
      });

      let bestMatch: { concept: any; similarity: number } | null = null;
      const threshold = 0.85;

      for (const candidate of candidates) {
        const similarity = jaroWinkler(
          name.toLowerCase(),
          candidate.canonicalName.toLowerCase()
        );

        if (similarity >= threshold && (!bestMatch || similarity > bestMatch.similarity)) {
          bestMatch = { concept: candidate, similarity };
        }

        // Check aliases
        for (const alias of candidate.aliases || []) {
          const aliasSim = jaroWinkler(name.toLowerCase(), alias.toLowerCase());
          if (aliasSim >= threshold && (!bestMatch || aliasSim > bestMatch.similarity)) {
            bestMatch = { concept: candidate, similarity: aliasSim };
          }
        }
      }

      if (bestMatch) {
        return {
          id: bestMatch.concept.id,
          canonicalName: bestMatch.concept.canonicalName,
          aliases: bestMatch.concept.aliases || [],
          description: bestMatch.concept.description || undefined,
          confidence: bestMatch.similarity,
          method: 'fuzzy',
        };
      }
    } catch (error) {
      console.error('Fuzzy match concept failed:', error);
    }

    return null;
  }

  /**
   * Semantic similarity match for concepts using pgvector
   */
  private async semanticMatchConcept(
    embedding: number[],
    userId: string
  ): Promise<CanonicalConcept | null> {
    try {
      const results = await this.prisma.$queryRaw<any[]>`
        SELECT id, canonical_name, aliases, description,
               1 - (embedding <=> ${JSON.stringify(embedding)}::vector) as similarity
        FROM concepts
        WHERE user_id = ${userId} AND embedding IS NOT NULL
        ORDER BY embedding <=> ${JSON.stringify(embedding)}::vector
        LIMIT 1
      `;

      if (results.length > 0 && results[0].similarity >= 0.92) {
        return {
          id: results[0].id,
          canonicalName: results[0].canonical_name,
          aliases: results[0].aliases || [],
          description: results[0].description,
          confidence: results[0].similarity,
          method: 'semantic',
        };
      }
    } catch (error) {
      console.error('Semantic match failed:', error);
    }

    return null;
  }

  /**
   * Stage 3: Wikidata lookup
   */
  private async wikidataLookup(name: string, type: string): Promise<CanonicalEntity | null> {
    try {
      const result = await this.wikidataClient.search(name, type);
      if (result) {
        return {
          id: '', // Will be generated by caller
          canonicalName: result.label,
          aliases: result.aliases,
          wikidataId: result.id,
          confidence: result.confidence,
          method: 'wikidata',
        };
      }
    } catch (error) {
      console.error('Wikidata lookup failed:', error);
    }
    return null;
  }

  /**
   * Stage 4: LLM canonicalization using GPT-4o-mini
   */
  private async llmCanonicalize(
    name: string,
    context: string,
    type: 'entity' | 'concept',
    entityType?: string
  ): Promise<{ canonicalName: string; reasoning: string }> {
    try {
      const prompt =
        type === 'entity'
          ? this.buildEntityPrompt(name, context, entityType!)
          : this.buildConceptPrompt(name, context);

      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o-mini',
        temperature: 0.0, // Deterministic
        messages: [
          { role: 'system', content: prompt.system },
          { role: 'user', content: prompt.user },
        ],
        response_format: { type: 'json_object' },
      });

      const result = JSON.parse(response.choices[0].message.content || '{}');
      return {
        canonicalName: result.canonical_name || name,
        reasoning: result.reasoning || '',
      };
    } catch (error) {
      console.error('LLM canonicalization failed:', error);
      // Fallback to input name
      return { canonicalName: name, reasoning: 'LLM failed, using original name' };
    }
  }

  /**
   * Build entity canonicalization prompt
   */
  private buildEntityPrompt(name: string, context: string, entityType: string) {
    return {
      system: `You are an entity normalization expert. Given an entity mention and context, provide the canonical (standard) form of the entity name.

Rules:
- Technology: Use official capitalization (e.g., "React", "PostgreSQL", "Node.js")
- Company: Use official legal name (e.g., "Meta Platforms" not "Facebook")
- Person: Use full name with proper capitalization (e.g., "Dan Abramov")
- Location: Use conventional geographic name (e.g., "New York City")
- Product: Use official product name (e.g., "ChatGPT", "iPhone")

Return JSON: { "canonical_name": "...", "reasoning": "..." }`,
      user: `Entity type: ${entityType}\nEntity mention: "${name}"\n\nContext:\n${context.substring(
        0,
        200
      )}`,
    };
  }

  /**
   * Build concept canonicalization prompt
   */
  private buildConceptPrompt(name: string, description: string) {
    return {
      system: `You are a concept normalization expert. Given a concept and description, provide the canonical (standard) form.

Rules:
- Use full form for abbreviations (e.g., "ML" → "Machine Learning")
- Use standard capitalization (e.g., "machine learning" → "Machine Learning")
- Prefer widely accepted terminology over jargon
- Use singular form unless plural is standard (e.g., "Web Development" not "Web Developments")

Return JSON: { "canonical_name": "...", "reasoning": "..." }`,
      user: `Concept: "${name}"\n\nDescription: ${description}`,
    };
  }

  /**
   * Stage 5: Cache the result
   */
  private async cacheResult(
    key: string,
    result: CanonicalEntity | CanonicalConcept,
    ttl: number = 7 * 24 * 60 * 60 // 7 days
  ): Promise<void> {
    try {
      await this.redis.setex(key, ttl, JSON.stringify(result));
    } catch (error) {
      console.error('Cache write failed:', error);
    }
  }

  /**
   * Disconnect all clients (cleanup)
   */
  async disconnect(): Promise<void> {
    await this.prisma.$disconnect();
    this.redis.disconnect();
  }
}
