import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';
import { Express } from 'express';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Smart Bookmarks API',
      version: '1.0.0',
      description: `
        AI-powered universal content capture and organization API with knowledge graph features.

        ## Features
        - 🔖 Bookmark management with automatic enrichment
        - 🤖 AI-powered content extraction and tagging
        - 🔍 Semantic search with vector embeddings
        - 🕸️ Knowledge graph with entities and concepts
        - 📊 Analytics and insights

        ## Authentication
        Supports two authentication methods:
        - **Cookie-based (session)**: Requires CSRF token for state-changing operations
        - **Bearer token (API)**: Stateless authentication, bypasses CSRF
      `,
      contact: {
        name: 'Smart Bookmarks Support',
        email: 'support@smartbookmarks.app',
      },
      license: {
        name: 'MIT',
        url: 'https://opensource.org/licenses/MIT',
      },
    },
    servers: [
      {
        url: 'http://localhost:3002',
        description: 'Development server',
      },
      {
        url: 'https://api.smartbookmarks.app',
        description: 'Production server',
      },
    ],
    components: {
      securitySchemes: {
        cookieAuth: {
          type: 'apiKey',
          in: 'cookie',
          name: 'accessToken',
          description: 'Cookie-based authentication (requires CSRF token for POST/PATCH/DELETE)',
        },
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'JWT Bearer token authentication (bypasses CSRF)',
        },
        csrfToken: {
          type: 'apiKey',
          in: 'header',
          name: 'X-CSRF-Token',
          description: 'CSRF token required for state-changing operations with cookie auth',
        },
      },
      schemas: {
        Error: {
          type: 'object',
          properties: {
            error: {
              type: 'string',
              description: 'Error type',
              example: 'Validation Error',
            },
            message: {
              type: 'string',
              description: 'Human-readable error message',
              example: 'Invalid input data',
            },
            details: {
              type: 'array',
              description: 'Detailed validation errors (if applicable)',
              items: {
                type: 'object',
                properties: {
                  field: {
                    type: 'string',
                    example: 'url',
                  },
                  message: {
                    type: 'string',
                    example: 'Invalid URL format',
                  },
                },
              },
            },
          },
        },
        Bookmark: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              format: 'uuid',
              description: 'Unique bookmark identifier',
            },
            userId: {
              type: 'string',
              format: 'uuid',
              description: 'Owner user ID',
            },
            url: {
              type: 'string',
              format: 'uri',
              description: 'Bookmark URL',
            },
            title: {
              type: 'string',
              description: 'Bookmark title',
            },
            domain: {
              type: 'string',
              description: 'Extracted domain',
            },
            summary: {
              type: 'string',
              nullable: true,
              description: 'AI-generated summary',
            },
            keyPoints: {
              type: 'array',
              items: { type: 'string' },
              description: 'Extracted key points',
            },
            contentType: {
              type: 'string',
              enum: ['article', 'video', 'social', 'document', 'other'],
              description: 'Content type',
            },
            status: {
              type: 'string',
              enum: ['pending', 'processing', 'completed', 'failed'],
              description: 'Enrichment status',
            },
            tags: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'string' },
                  name: { type: 'string' },
                  autoGenerated: { type: 'boolean' },
                },
              },
              description: 'Associated tags',
            },
            createdAt: {
              type: 'string',
              format: 'date-time',
            },
            updatedAt: {
              type: 'string',
              format: 'date-time',
            },
            processedAt: {
              type: 'string',
              format: 'date-time',
              nullable: true,
            },
          },
          required: ['id', 'userId', 'url', 'title', 'domain', 'contentType', 'status'],
        },
        User: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              format: 'uuid',
            },
            email: {
              type: 'string',
              format: 'email',
            },
            emailVerified: {
              type: 'boolean',
            },
            role: {
              type: 'string',
              enum: ['user', 'admin'],
            },
            createdAt: {
              type: 'string',
              format: 'date-time',
            },
            updatedAt: {
              type: 'string',
              format: 'date-time',
            },
          },
        },
        Entity: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            normalizedName: { type: 'string' },
            entityType: {
              type: 'string',
              enum: ['person', 'company', 'technology', 'location', 'product'],
            },
            occurrenceCount: { type: 'integer' },
            firstSeenAt: { type: 'string', format: 'date-time' },
            lastSeenAt: { type: 'string', format: 'date-time' },
          },
        },
        Concept: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            normalizedName: { type: 'string' },
            parentConceptId: { type: 'string', format: 'uuid', nullable: true },
            occurrenceCount: { type: 'integer' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
      },
      responses: {
        UnauthorizedError: {
          description: 'Access token is missing or invalid',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
              example: {
                error: 'Unauthorized',
                message: 'Authentication required',
              },
            },
          },
        },
        ForbiddenError: {
          description: 'CSRF token is missing or invalid',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
              example: {
                error: 'CSRF token missing',
                message: 'Include X-CSRF-Token header in your request',
              },
            },
          },
        },
        ValidationError: {
          description: 'Invalid request parameters',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
              example: {
                error: 'Validation Error',
                message: 'Invalid input data',
                details: [
                  {
                    field: 'url',
                    message: 'Invalid URL format',
                  },
                ],
              },
            },
          },
        },
        NotFoundError: {
          description: 'Resource not found',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
              example: {
                error: 'Not Found',
                message: 'Bookmark not found',
              },
            },
          },
        },
        RateLimitError: {
          description: 'Too many requests',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
              example: {
                error: 'Too Many Requests',
                message: 'Rate limit exceeded. Please try again later.',
              },
            },
          },
        },
      },
    },
    tags: [
      {
        name: 'Authentication',
        description: 'User authentication and session management',
      },
      {
        name: 'Bookmarks',
        description: 'Bookmark CRUD operations',
      },
      {
        name: 'Enrichment',
        description: 'Content enrichment and AI processing',
      },
      {
        name: 'Search',
        description: 'Semantic and keyword search',
      },
      {
        name: 'Knowledge Graph',
        description: 'Graph queries, entities, concepts, and relationships',
      },
      {
        name: 'Profile',
        description: 'User profile management',
      },
      {
        name: 'Admin',
        description: 'Administrative operations (admin only)',
      },
    ],
  },
  // Path to API route files for annotation scanning
  apis: ['./src/routes/*.ts', './src/routes/**/*.ts'],
};

// Generate OpenAPI specification
const swaggerSpec = swaggerJsdoc(options);

/**
 * Setup Swagger UI and API documentation endpoints (Admin only)
 */
export function setupSwagger(app: Express, ...authMiddlewares: any[]): void {
  // Serve Swagger UI at /api/docs (protected by admin auth)
  app.use('/api/docs', ...authMiddlewares, swaggerUi.serve, swaggerUi.setup(swaggerSpec, {
    customCss: '.swagger-ui .topbar { display: none }',
    customSiteTitle: 'Smart Bookmarks API Documentation',
  }));

  // Serve raw OpenAPI spec as JSON at /api/docs.json (protected by admin auth)
  app.get('/api/docs.json', ...authMiddlewares, (req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
  });

  console.log('📚 API Documentation available at (Admin only):');
  console.log('   Swagger UI:    /api/docs');
  console.log('   OpenAPI JSON:  /api/docs.json');
}

export default swaggerSpec;
